coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        flags:
          - unit
        paths:
          - "fourparts"
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false