SAMPLE_DIR = "samples/"
CSV_EXTENSION = ".csv"
MIDI_EXTENSION = ".mid"


CHORALE_F = "chorale_F"
CHORALE_F_CSV = SAMPLE_DIR + CHORALE_F + CSV_EXTENSION
CHORALE_F_MIDI = SAMPLE_DIR + CHORALE_F + MIDI_EXTENSION

CHORALE_G_2PARTS = "chorale_G_2parts"
CHORALE_G_2PARTS_CSV = SAMPLE_DIR + CHORALE_G_2PARTS + CSV_EXTENSION
CHORALE_G_2PARTS_MIDI = SAMPLE_DIR + CHORALE_G_2PARTS + MIDI_EXTENSION

DISPLACED = "displaced"
DISPLACED_CSV = SAMPLE_DIR + DISPLACED + CSV_EXTENSION
DISPLACED_MIDI = SAMPLE_DIR + DISPLACED + MIDI_EXTENSION

PERFECT_CADENCE = "perfect_cadence"
PERFECT_CADENCE_CSV = SAMPLE_DIR + PERFECT_CADENCE + CSV_EXTENSION
PERFECT_CADENCE_MIDI = SAMPLE_DIR + PERFECT_CADENCE + MIDI_EXTENSION

TYPEA_PERFECT_CADENCE = "typeA_perfect_cadence"
TYPEA_PERFECT_CADENCE_CSV = SAMPLE_DIR + TYPEA_PERFECT_CADENCE + CSV_EXTENSION
TYPEA_PERFECT_CADENCE_MIDI = SAMPLE_DIR + TYPEA_PERFECT_CADENCE + MIDI_EXTENSION

UNISON = "unison"
UNISON_CSV = SAMPLE_DIR + UNISON + CSV_EXTENSION
UNISON_MIDI = SAMPLE_DIR + UNISON + MIDI_EXTENSION
